version: '3.8'
services:
  fastapi-app:
    build: .
    network_mode: "host"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
  nginx:
    image: nginx:latest
    network_mode: "host"
    ports:
      - "8080:80"
    volumes:
      - ./confs/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - fastapi-app