version: '3.8'
services:
  fastapi-app:
    build: .
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./confs/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - fastapi-app